#!/usr/bin/env bash
#
# Build the single binary.
#
#   shell/build.sh [outdir]
#
# Produces dist/deskpilot — the runtime, the server and the built web UI in one
# file, so a target machine needs neither deno nor npm. Runtime helper scripts
# are copied beside it rather than embedded: desk.sh is the compositor-specific
# half, and keeping it readable is what makes another compositor a contribution
# rather than a rewrite.
#
# The commit is baked in, so a binary can say exactly what it is even though it
# has no .git to read.
#
# One permission is deliberately wider here than when running from source:
# --allow-write is unscoped. The state directory is under $HOME, and $HOME is
# not knowable when the binary is built — baking the builder\'s path in meant
# the binary silently failed to persist anything for every other user, which is
# how a device could pair, work, and then not exist after a restart. Everything
# else stays scoped, and writes are still confined by the OS to what the service
# user can reach.

set -uo pipefail
REPO="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
OUT="${1:-$REPO/dist}"
# Where desk.sh will live on the target. Fixed at build time because a compiled
# binary's --allow-run allowlist is fixed at build time: it can only execute the
# path it was compiled to allow. The default is the packaged location.
SCRIPTS_TARGET="${2:-/usr/share/deskpilot/scripts}"
cd "$REPO" || exit 1

command -v deno >/dev/null || { echo "deno is required to build" >&2; exit 1; }

echo "==> building the web UI"
(cd web && npm run build) >/dev/null 2>&1 || { echo "web build failed" >&2; exit 1; }

mkdir -p "$OUT/scripts"

echo "==> compiling (desk.sh expected at $SCRIPTS_TARGET)"
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "")
INFO="$REPO/server/build-info.ts"
cp "$INFO" "$INFO.orig"
cat > "$INFO" <<INNER
// Generated by shell/build.sh — do not edit. See build-info.ts in git for why.
export const COMMIT = "$COMMIT";
export const SCRIPTS_DIR = "$SCRIPTS_TARGET";
INNER

deno compile \
  --output "$OUT/deskpilot" \
  --include "$REPO/web/dist" \
  --allow-net \
  --allow-read \
  --allow-env \
  --allow-write \
  --allow-run=tmux,ps,hyprctl,systemctl,"$SCRIPTS_TARGET/desk.sh","$SCRIPTS_TARGET/session.sh" \
  server/server.ts
rc=$?
mv "$INFO.orig" "$INFO"
[ $rc -eq 0 ] || exit 1

# Staged for packaging, under the path the binary was compiled to allow — not
# next to the binary. A copy beside it would be found first by anything that
# searches and then refused by the allowlist, which reads as "no compositor
# here" with a working desk.sh in plain sight.
cp "$REPO/scripts/desk.sh" "$OUT/scripts/desk.sh"
cp "$REPO/scripts/sessions.sh" "$OUT/scripts/sessions.sh"
cp "$REPO/scripts/session.sh" "$OUT/scripts/session.sh"
chmod +x "$OUT/scripts/"*.sh
echo "    (install these to $SCRIPTS_TARGET — the binary can execute no other copy)"

echo
echo "  $OUT/deskpilot        $(du -h "$OUT/deskpilot" | cut -f1)"
echo "  $OUT/scripts/*.sh     (runtime helpers, not embedded)"
echo
echo "Install the scripts before running it — the binary's allowlist is fixed at"
echo "compile time, so only helper copies under $SCRIPTS_TARGET may execute:"
echo
echo "  sudo install -Dm755 $OUT/scripts/*.sh -t $SCRIPTS_TARGET/"
echo "  $OUT/deskpilot setup"
